/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EventCategory = IDL.Variant({
  'entertainment' : IDL.Null,
  'travel' : IDL.Null,
  'events' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : EventCategory,
  'location' : IDL.Text,
});
export const TravelPackage = IDL.Record({
  'id' : IDL.Nat,
  'destination' : IDL.Text,
  'featured' : IDL.Bool,
  'duration' : IDL.Text,
  'highlights' : IDL.Vec(IDL.Text),
  'priceRange' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'clientName' : IDL.Text,
  'quote' : IDL.Text,
  'company' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ServiceType = IDL.Variant({
  'entertainment' : IDL.Null,
  'travel' : IDL.Null,
  'events' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getFeaturedEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getFeaturedPackages' : IDL.Func([], [IDL.Vec(TravelPackage)], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getTravelPackages' : IDL.Func([], [IDL.Vec(TravelPackage)], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EventCategory = IDL.Variant({
    'entertainment' : IDL.Null,
    'travel' : IDL.Null,
    'events' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : EventCategory,
    'location' : IDL.Text,
  });
  const TravelPackage = IDL.Record({
    'id' : IDL.Nat,
    'destination' : IDL.Text,
    'featured' : IDL.Bool,
    'duration' : IDL.Text,
    'highlights' : IDL.Vec(IDL.Text),
    'priceRange' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'clientName' : IDL.Text,
    'quote' : IDL.Text,
    'company' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ServiceType = IDL.Variant({
    'entertainment' : IDL.Null,
    'travel' : IDL.Null,
    'events' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  
  return IDL.Service({
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getFeaturedEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getFeaturedPackages' : IDL.Func([], [IDL.Vec(TravelPackage)], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getTravelPackages' : IDL.Func([], [IDL.Vec(TravelPackage)], ['query']),
    'seedSampleData' : IDL.Func([], [], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };