/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'date' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : EventCategory,
  'location' : string,
}
export type EventCategory = { 'entertainment' : null } |
  { 'travel' : null } |
  { 'events' : null };
export type Result = { 'ok' : bigint } |
  { 'err' : string };
export type ServiceType = { 'entertainment' : null } |
  { 'travel' : null } |
  { 'events' : null };
export interface TeamMember {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'role' : string,
  'imageUrl' : string,
}
export interface Testimonial {
  'id' : bigint,
  'clientName' : string,
  'quote' : string,
  'company' : string,
  'rating' : bigint,
}
export interface TravelPackage {
  'id' : bigint,
  'destination' : string,
  'featured' : boolean,
  'duration' : string,
  'highlights' : Array<string>,
  'priceRange' : string,
  'imageUrl' : string,
}
export interface _SERVICE {
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getFeaturedEvents' : ActorMethod<[], Array<Event>>,
  'getFeaturedPackages' : ActorMethod<[], Array<TravelPackage>>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getTravelPackages' : ActorMethod<[], Array<TravelPackage>>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'submitInquiry' : ActorMethod<
    [string, string, string, ServiceType, string],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];